import {
  FETCH_CONTACT,
  FETCH_EDUCATION,
  FETCH_EXPERIENCE, FETCH_FREE_TIME,
  FETCH_INTRO,
  FETCH_LINKS,
  FETCH_SEARCH_MESSAGE, FETCH_SKILLS,
  GET_TYPE_OF_RESUME, SET_DETAIL,
  TURN_OFF_ANIMATION
} from "../actions";

export const type = {
  [GET_TYPE_OF_RESUME]: GET_TYPE_OF_RESUME,
  [FETCH_SEARCH_MESSAGE]: FETCH_SEARCH_MESSAGE,
  [TURN_OFF_ANIMATION]: TURN_OFF_ANIMATION,
  [FETCH_LINKS]: FETCH_LINKS,
  [FETCH_INTRO]: FETCH_INTRO,
  [FETCH_EXPERIENCE]: FETCH_EXPERIENCE,
  [FETCH_EDUCATION]: FETCH_EDUCATION,
  [FETCH_SKILLS]: FETCH_SKILLS,
  [FETCH_FREE_TIME]: FETCH_FREE_TIME,
  [FETCH_CONTACT]: FETCH_CONTACT,
  [SET_DETAIL]: SET_DETAIL,
}

type Type = keyof typeof type;

export default interface IAction<T = any> {
  type: Type;
  payload: T;
}
